// Cloudflare entry: serves the Next.js app and runs the daily job (see wrangler.jsonc "triggers").
// @ts-expect-error — generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,
  async scheduled(_event: unknown, env: { APP_URL: string; CRON_SECRET: string }, ctx: { waitUntil(p: Promise<unknown>): void }) {
    const req = new Request(`${env.APP_URL}/api/cron/daily`, { headers: { authorization: `Bearer ${env.CRON_SECRET}` } });
    ctx.waitUntil(handler.fetch(req, env, ctx));
  },
};
